local	MusicSounds = {
			{
				SoundName = "Cartoon Jéja On On feat Daniel Levi Electronic Pop NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Cartoon%20J%C3%A9ja%20%20On%20%20On%20feat%20Daniel%20Levi%20%20Electronic%20Pop%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
			{
				SoundName = "Cartoon Jéja Why We Lose feat Coleman Trapp DnB NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Cartoon%20J%C3%A9ja%20%20Why%20We%20Lose%20feat%20Coleman%20Trapp%20%20DnB%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
			{
				SoundName = "DEAF KEV Invincible Glitch Hop NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/DEAF%20KEV%20%20Invincible%20%20Glitch%20Hop%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
			{
				SoundName = "Different Heaven EHDE My Heart Drumstep NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Different%20Heaven%20%20EHDE%20%20My%20Heart%20%20Drumstep%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
			{
				SoundName = "ElectroLight Symbolism Trap NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/ElectroLight%20%20Symbolism%20%20Trap%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
			{
				SoundName = "Elektronomia Sky High Progressive House NCS Copyright Free Music.mp3",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Elektronomia%20%20Sky%20High%20%20Progressive%20House%20%20NCS%20%20Copyright%20Free%20Music.mp3"
			};
}
return MusicSounds
