--[Not really characters just humanoid descriptions which are then applied onto your character]

local	CharacterModels = {
	{
		CharacterName = "Roblox";
		CharacterType = "User";
		CharacterID = 1;
	};
	{
		CharacterName = "Mightybaseplate";
		CharacterType = "User";
		CharacterID = 9960695;
	};
	{
		CharacterName = "TCtully";
		CharacterType = "User";
		CharacterID = 7928245;
	};
	{
		CharacterName = "MidnightKrystal";
		CharacterType = "User";
		CharacterID = 47939131;
	};
	{
		CharacterName = "Bluay";
		CharacterType = "User";
		CharacterID = 2820112;
	};
	{
		CharacterName = "Scapter";
		CharacterType = "User";
		CharacterID = 3436218611;
	};
	{
		CharacterName = "Xonae";
		CharacterType = "User";
		CharacterID = 52187831;
	};
	{
		CharacterName = "Castlers";
		CharacterType = "User";
		CharacterID = 49405424;
	};
	{
		CharacterName = "Zeenyoo";
		CharacterType = "User";
		CharacterID = 30926698;
	};
	{
		CharacterName = "DevRolve";
		CharacterType = "User";
		CharacterID = 23239501;
	};
	{
		CharacterName = "MidnightKrystal";
		CharacterType = "User";
		CharacterID = 47939131;
	};
	{
		CharacterName = "MidnightKrystal";
		CharacterType = "User";
		CharacterID = 47939131;
	};
	{
		CharacterName = "MidnightKrystal";
		CharacterType = "User";
		CharacterID = 47939131;
	};
}

return CharacterModels
