local	HitSounds = {
			{
				SoundName = "Minecraft Hit",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Minecraft%20Hit%20Sound.mp3"
			};
			{
				SoundName = "Minecraft Bow Ding",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Minecraft%20Bow%20Hit.mp3"
			};
			{
				SoundName = "Minecraft Click",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Minecraft%20Click.mp3"
			};
			{
				SoundName = "Minecraft Xp Gain",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Minecraft%20Xp%20Gain.mp3"
			};
			{
				SoundName = "Quaver",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/quaver.mp3"
			};
			{
				SoundName = "Aim Booster",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/aimbooster.mp3"
			};
			{
				SoundName = "Ting",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/ting.mp3"
			};
			{
				SoundName = "Pop",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/pop.mp3"
			};
			{
				SoundName = "Satisfying Click",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/satisfying%20click.mp3"
			};
			{
				SoundName = "Trident Pierce",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/trident%20pierce.mp3"
			};
			{
				SoundName = "Water Drop",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/water%20drop.mp3"
			};
			{
				SoundName = "Bonk",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/bonk.mp3"
			};
			{
				SoundName = "Hitmarker",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/hitmarker.mp3"
			};
			{
				SoundName = "Bamboo",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/bamboo%20hit.mp3"
			};
		};
return HitSounds
