local	KillSounds = {
			{
				SoundName = "Minceraft Oof",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Minecraft%20Damage.mp3"
			};
			{
				SoundName = "Humiliation",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Humiliation.mp3"
			};
			{
				SoundName = "Fatality",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Mortal%20Kombat%20Fatality.mp3"
			};
			{
				SoundName = "Vine Boom",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Vine%20Boom.mp3"
			};
			{
				SoundName = "Zeus",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/csgo%20zeus.mp3"
			};
			{
				SoundName = "TF2 Crit",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/tf2%20crit%20hit.mp3"
			};
			{
				SoundName = "Among Us",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/among%20us%20kill%20sound.mp3"
			};
			{
				SoundName = "TF2 Kill",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/tf2%20kill%20sound.mp3"
			};
			{
				SoundName = "Hit Or Miss",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/hit%20or%20miss.MP3"
			};
			{
				SoundName = "Valorant",
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Valorant%20kill.mp3"
			};
		};
return KillSounds
