--[Hi, thanks for using funswapper.vip!]

local MusicKits = {
	{
		KitName = "Flashbang Dance";
		KitData = {
			{
				SoundName = "Mvp.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Mvp.mp3";
			};
			
			{
				SoundName = "Bomb Planted.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Bomb%20Planted.mp3";
			};
			
			{
				SoundName = "Bomb 10 Seconds.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Bomb10Sec.mp3";
			};
			
			{
				SoundName = "Choose Team.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Choose%20Team.mp3";
			};
			
			{
				SoundName = "Death Cam.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Death%20Cam.mp3";
			};
			
			{
				SoundName = "Menu.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Menu.mp3";
			};
			
			{
				SoundName = "Mvp.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Mvp.mp3";
			};
			
			{
				SoundName = "Round Lost.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Round%20Lost.mp3";
			};
			
			{
				SoundName = "Round Won.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Round%20Won.mp3";
			};
			
			{
				SoundName = "Round 10 Seconds.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_Round10Seconds.mp3";
			};
			
			{
				SoundName = "Start Action1.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_StartAction1.mp3";
			};
			
			{
				SoundName = "Start Action2.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_StartAction2.mp3";
			};
			
			{
				SoundName = "Start Round1.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_StartRound1.mp3";
			};
			
			{
				SoundName = "Start Round2.mp3";
				SoundLink = "https://github.com/Funswapper/Funswapper.vip/raw/refs/heads/main/CustomAssets/Flashbang%20Dance_StartRound2.mp3";
			};
		}
	}
}

return MusicKits
